homeassistant:
  customize:
    package.node_anchors:
        Allarme: &alarm alarm_control_panel.home_alarm
        Campanello: &doorbell switch.campanello

# SE SCATTA ALLARME FAI SUONARE IL CAMPANELLO AD INTERMITTENZA
automation:
- alias: Campanello come allarme
  id: bell_for_alarm
  mode: restart
  trigger:
  - entity_id: *alarm
    platform: state
    to: 
      - triggered
      - disarmed
  action:
  - alias: Attiva campanello per allarme scattato
    if: 
        - "{{trigger.to_state.state == 'triggered'}}"
    then:
        - repeat:
            count: '60'
            sequence:
            - service: switch.toggle
              target:
                entity_id: *doorbell
            - delay:
                seconds: 1
        - service: switch.turn_off
          target:
            entity_id: *doorbell

    else:
        - service: switch.turn_off
          target:
            entity_id: *doorbell
