homeassistant:
  customize:
    package.node_anchors:
        Allarme: &alarm alarm_control_panel.home_alarm
        Gruppo tutte le luci: &all_light group.tutte_le_luci

automation: 
- alias: Allarme globale inserito spegni casa
  id: alarm_global_insert_turn_off
  variables:
    all_light: *all_light
  trigger:
  - platform: state
    entity_id: *alarm
    from: 'arming'
    to: 'armed_away'
  action:  
  # - alias: Spegne i televisori
  #   service: media_player.turn_off
  #   target:
  #     entity_id: 
  #       - media_player.samsung_qled_49
  #       - media_player.philips55
  #       - media_player.playstation_4
  #       - media_player.samsung_ue40d6500

  - alias: Spegni tutte le luci
    service: homeassistant.turn_off
    target:
      entity_id: "{{expand(all_light)|map(attribute='entity_id')|list}}"

  - alias: Spegni Clima Camera
    if: "{{is_state('binary_sensor.condizionatore_camera_power','on')}}"
    then:
      - service: climate.turn_off
        target:
          entity_id: climate.camera_ac
  - alias: Spegni Clima Sala
    if: "{{is_state('binary_sensor.condizionatore_sala_power','on')}}"
    then:
      - service: climate.turn_off
        target:
          entity_id: climate.condizionatore_salone
  - alias: Spegni Dyson
    if: "{{is_state('fan.salotto','on')}}"
    then:
      - service: fan.turn_off
        target:
          entity_id: fan.salotto
